on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs: { }

jobs:
  publish:
    name: "Publish to Docker Hub"
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Load cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: docker-file-server

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v3
      with:
        tags: ${{ vars.DOCKER_HUB_REPO }}/file-server
        platforms: linux/amd64,linux/arm64
        push: true
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        cache-from: type=local,src=/tmp/.buildx-cache

    - name: Replace cache  # temp fix for https://github.com/docker/build-push-action/issues/252 & https://github.com/moby/buildkit/issues/1896.
      run: rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache